---
- name: Create /etc/docker dir
  file:
    path: /etc/docker
    owner: root
    mode: 0755
    state: directory
    group: root

- name: Configure docker daemon
  template:
    src: templates/daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
